### ISSUE TITLE
JSDOM not available in tests

### ISSUE THREAD

**Issue by atty-stripe** [simon360/jest-environment-jsdom-global#4]
For some reason, `jsdom` isn't defined when I run my tests with this environment. Per the [documentation](https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string), I used `global.jsdom` instead, and then it says `global.jsdom` is undefined.

I'm trying to use `jsdom.reconfigure` to change the URL in one of my tests.

**Comment by simon360** [comment]
@atty-stripe could you please post some example code for the test you're trying to run? Thanks!

**Comment by atty-stripe** [comment]
Unfortunately can't share the actual test code, but here's the gist:

```js
it('tests some functionality', () => {
  global.jsdom.reconfigure({
    url: 'https://kfc.com/order-chicken',
  });

  // Test for functionality that requires HTTPS
});
```

**Comment by simon360** [comment]
Hm, that's strange. That ought to work.

Are you setting the environment using the `testEnvironment` property in your Jest configuration, or are you using an `@jest-environment` docblock? What version of Jest and Node are you using?

Is there any way you can reproduce this bug on a smaller scale, and either put it in a repo or post the files here, so that I can take a look at what's happening and test it locally? 

I understand not being able to share the _actual_ code, but on my end, it's difficult to debug without more information. I suspect it will have something to do with your development environment/project structure, since that test looks correct (I'm not trying to avoid blame here - this project aims to support as many setups as possible, but naturally, it's impossible to know all of them beforehand).

**Comment by atty-stripe** [comment]
Absolutely, I understand! Will try to post a minimal repro.

**Comment by jcrben** [comment]
I thought I was having the same issue, but it turned out I'd accidentally nested the configuration into the globals config (not a fan of 2 space indentation).

**Comment by atty-stripe** [comment]
This was a bug on my side! My test running script manually overrode the environment, so the environment from the config wasn't being used. Sorry for the false alarm!
